# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ilker Bozcan blog
email: ilkerbozcan@hotmail.com, bozcan.ilker@metu.edu.tr
description: > # this means to ignore newlines until "baseurl:"
  My humble blog about robotics, computer science and philosophy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bozcani.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  bozcani

# Build settings
markdown: kramdown
